name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install coverage flake8

      - name: Ejecutar tests con coverage
        run: |
          coverage run -m unittest discover -s calculadoraClase1/tests -p "test_*.py"
          coverage report -m
          coverage xml


      - name: Análisis estático con Flake8
        run: |
          flake8 . --max-line-length=120 --exclude=.github